package com.theerthkr.essentialmoments

// In ObjectBox.kt
object ObjectBox {
    lateinit var store: io.objectbox.BoxStore
        private set

    fun init(context: android.content.Context) {
        // 'MyObjectBox' is a class generated by ObjectBox after you build the project
        store = MyObjectBox.builder()
            .androidContext(context.applicationContext)
            .build()
    }
}

// In App.kt
class App : android.app.Application() {
    override fun onCreate() {
        super.onCreate()
        ObjectBox.init(this) // Initialize the database once for the whole app[cite: 5]
    }
}